#!/bin/ash

# $1 is -c when run from DCE.

case $2 in
    install-bash)
        ln -s /bin/sh /bin/bash
        echo "Installed bash"
        exit
        ;;
    install-fish)
        ln -s /bin/sh /usr/bin/fish
        echo "Installed fish"
        exit
        ;;
esac

if [ "$1" = '-c' ]; then
    exec /bin/ash -c "$2"
    exit
fi

echo "This is $0"

