name: Run tests and publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [3.2, 3.3, 3.4]
    steps:
    - uses: actions/checkout@v5
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Prepare fixtures
      run: |
        cd features/fixtures/shell
        docker compose build
    - name: Run Cucumber tests
      run: |
        gem install cucumber simplecov-cobertura
        export PATH=$PATH:$PWD
        cucumber

    - uses: codecov/codecov-action@v4
      with:
        # Needed for Dependabot PRs.
        token: ${{ secrets.CODECOV_TOKEN }}
        # fail_ci_if_error: true # optional (default = false)

  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/checkout@v5
    - name: Set up Ruby 3.3
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3

    - name: Publish to RubyGems
      run: |
        # Replace version in gemspec with tag name.
        sed -i s/VERSION/${GITHUB_REF/refs\/tags\//}/ dce.gemspec
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
